apiVersion: apps/v1
kind: Deployment
metadata:
  name: pd-scanner-api
  labels:
    app: pd-scanner
    component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: pd-scanner
      component: api
  template:
    metadata:
      labels:
        app: pd-scanner
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn"]
          args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: CELERY_BROKER_URL
              value: "redis://pd-scanner-redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://pd-scanner-redis:6379/0"
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@pd-scanner-postgresql:5432/{{ .Values.postgresql.auth.database }}" 