{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pd-scanner-postgresql
  labels:
    app: pd-scanner
    component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pd-scanner
      component: postgresql
  template:
    metadata:
      labels:
        app: pd-scanner
        component: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: pd-scanner-postgresql
  labels:
    app: pd-scanner
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: pd-scanner
    component: postgresql
{{- end }} 